name: flutter_practice
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icon
  cupertino_icons: ^1.0.8

  # Bottom draggable container
  drag_container: ^2.0.0

  # Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  rxdart: ^0.27.7

  # Input Form
  equatable: ^2.0.5
  uuid: ^4.4.0
  formz: ^0.7.0

   # Network
  dio: ^5.4.3+1
  stream_transform: ^2.1.0
  json_annotation: ^4.6.0
  http: ^0.13.0
  freezed_annotation: ^2.0.0

  # Image & Camera
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0

  audioplayers: ^6.1.0

  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  # Bloc
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  test: ^1.24.9
  mockingjay: ^0.5.0

  # JSON model builder
  build_runner: ^2.0.0
  flutter_gen_runner: any
  json_serializable: ^6.3.1

  freezed: ^2.0.0

  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

#  fonts:
#    - family: Raleway
#      fonts:
#        - asset: assets/fonts/Raleway-Regular.ttf
#        - asset: assets/fonts/Raleway-Italic.ttf
#          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
