name: flutter_practice
description: 一個新的 Flutter 專案
# 以下行防止此套件意外發布到 pub.dev，適用於私有套件。如果需要發布到 pub.dev，請移除此行。
publish_to: 'none'

# 定義應用的版本和構建號
# 版本號格式為三段式（例如：1.2.43），可選的構建號用 "+" 分隔（例如：1.2.43+1）
# Android 上：build-name 用作 versionName，build-number 用作 versionCode
# iOS 上：build-name 用作 CFBundleShortVersionString，build-number 用作 CFBundleVersion
# Windows 上：build-name 分別作為產品版本和文件版本的主次版本，而 build-number 作為後綴
version: 1.0.0+1

# 定義 Dart SDK 的版本範圍
environment:
  sdk: '>=3.0.2 <4.0.0'

# 項目的依賴項
dependencies:
  flutter:
    sdk: flutter
  # Flutter 本地化支持
  flutter_localizations:
    sdk: flutter
  # Dart 國際化工具包
  intl: ^0.20.2 # 用於日期、數字和消息的格式化和本地化


  # 本地存儲套件
  shared_preferences: ^2.5.3

  # 底部可拖動容器
  drag_container: ^2.0.0

  # 狀態管理工具包
  rxdart: ^0.28.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  # 表單處理
  equatable: ^2.0.5
  uuid: ^4.5.1
  formz: ^0.7.0

  # 網絡通信相關套件
  dio: ^5.8.0+1
  stream_transform: ^2.1.0
  json_annotation: ^4.9.0
  http: ^1.0.0
  freezed_annotation: ^2.0.0

  # Retrofit HTTP 客戶端生成器
  retrofit: ^4.4.1
  logger: ^2.5.0 # 用於日誌輸出

  # 圖片與相機處理
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0

  # 音頻處理工具
  audioplayers: ^6.1.0

  # Url文字樣式顯示
  flutter_linkify: ^6.0.0
  # 網址啟動支持
  url_launcher: ^6.2.5

  # 權限要求處理
  permission_handler: ^12.0.0+1
  # 照片選擇工具
  image_picker: ^1.1.2

  # Toast提示套件
  toast: ^0.3.0

  # Go Router 路由管理套件
  go_router: ^16.0.0

  # 約束佈局套件
  flutter_constraintlayout: ^1.7.0-stable

  # Firebase 核心套件
  firebase_core: ^3.14.0
  # Firebase 分析套件
  firebase_analytics: ^11.5.0
  # Firebase 推播通知套件
  firebase_messaging: ^15.2.7
  # Firebase 穩定度分析套件
  firebase_crashlytics: ^4.3.7
    # Firebase 身份驗證套件
  firebase_app_installations: ^0.3.2+7


  # 本地存儲套件（使用專案內的 packages）
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository


# 開發時依賴的套件
dev_dependencies:
  flutter_test:
    sdk: flutter

  # 國際化工具
  intl_translation: ^0.20.1
  intl_utils: ^2.8.2

  # Flutter Lint規則
  flutter_lints: ^3.0.2

  # Bloc 測試工具
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test: ^1.25.15
  mockingjay: ^2.0.0

  # Provider
  provider: ^6.1.5

  # 構建驗證工具，用於檢查代碼生成是否與源代碼同步
  build_runner: ^2.4.13
  build_verify: ^3.1.1
  # 圖像, 色碼,
  flutter_gen_runner: any

  # JSON 模型生成工具
  json_serializable: ^6.9.0

  # Go Router 路由代碼生成器
  go_router_builder: ^3.0.1

  # Retrofit 生成器
  retrofit_generator: ^9.1.5

  # Freezed 生成器
  freezed: ^2.0.0

  # Google 字體工具
  google_fonts: ^6.2.1

# Flutter 自動生成相關的配置
flutter_gen:
  output: lib/gen/ # 自動生成代碼的輸出路徑 (默認為 lib/gen/)
  line_length: 80 # 每行的最大字符長度 (默認為 80)

  # 集成多種類型的資源支持 (選填項)
  integrations:
    flutter_svg: true
    image: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml # 定義顏色的 XML 檔案

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output_dir: lib/l10n/generated
  main_locale: zh

# Flutter 專有的配置項
flutter:
    # 啟用自動生成代碼的功能
  generate: false

  # 引入 Material Design 圖標字體以支持 material Icons 類
  uses-material-design: true

  # 資源文件，如圖像，可以在此定義
  assets:
    - assets/images/

  # 字體設定（如需自定義字體，可以取消以下的註解）
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic
